Workaround docker image limitation by installing autoconf,automake,gawk at initialization.

diff --git a/cygwin-shell b/cygwin-shell
--- a/cygwin-shell
+++ b/cygwin-shell
@@ -7,6 +7,13 @@ then
     set -x
 fi
 
+if [ "${DISPLAY}" = "" ]
+then
+    export DISPLAY=:95
+    Xvfb :95 -ac -reset -terminate -screen 0 800x600x16 2>/dev/null &
+    sleep 3
+fi
+
 # workaround https://bugs.wine-staging.com/show_bug.cgi?id=403
 if [ "${DRONE}" = "true" ]
 then
@@ -16,13 +23,12 @@ then
     fi
     export WINEPREFIX=/drone/wineprefix
     export CYGWIN_ROOT=${WINEPREFIX}/drive_c/${CYGWIN_DIR}
-fi
 
-if [ "${DISPLAY}" = "" ]
-then
-    export DISPLAY=:95
-    Xvfb :95 -ac -reset -terminate -screen 0 800x600x16 2>/dev/null &
-    sleep 3
+    echo FIXME - Workaround docker image limitation
+    echo "These packages can't be preinstalled inside docker image because docker image does not support cygwin symlink."
+    echo wine c:/cygwin-installer.exe --site http://mirrors.tea-ci.org/cygwin --local-package-dir Z:/tmp/cygwin -W -P autoconf,automake,gawk -q
+    WINEDEBUG=-all wine c:/cygwin-installer.exe --site http://mirrors.tea-ci.org/cygwin --local-package-dir Z:/tmp/cygwin -W -P autoconf,automake,gawk -q &> /dev/null
+    echo
 fi
 
 if [ "$1" = "-h" ] || [ "$1" = "--help" ]
